Repository baduhai/Koi, pull requests merged in 2025-04, with the labels that each got.

#105 [BUG] not all kvantum themes are showing #98
  src/plugins/kvantumstyle.cpp
Labels: Bug, Suggestion

#106 Add DBus interface for changing light/dark mode
  src/CMakeLists.txt
  src/dbusinterface.cpp
  src/headers/dbusinterface.h
  src/main.cpp
Labels: Feature Request, Suggestion

#109 chore: removes QTest as dependency
  README.md
  src/CMakeLists.txt
  src/headers/utils.h
  src/utils.cpp
Labels: Feature Request, Suggestion

#110 do not start scheduler when there is no schedule defined
  src/headers/mainwindow.h
  src/mainwindow.cpp
Labels: Suggestion, Added/Changed Features/Options

#108 Several memory leak fixes; and does not start krunner as a child process
  src/headers/plugin.h
  src/headers/utils.h
  src/main.cpp
  src/mainwindow.cpp
  src/plugins/colorscheme.cpp
  src/plugins/colorscheme.h
  src/plugins/gtk.cpp
  src/plugins/icons.cpp
  src/plugins/icons.h
  src/plugins/kvantumstyle.cpp
  src/plugins/kvantumstyle.h
  src/plugins/plasmastyle.cpp
  src/plugins/plasmastyle.h
  src/plugins/script.cpp
  src/plugins/script.h
  src/plugins/wallpaper.cpp
  src/utils.cpp
Labels: Bug, Invalid, Suggestion, Added/Changed Features/Options
